version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=user
      - TZ=Asia/Seoul
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5434:5432"

